package com.edu.netbeans.proyectoprograv2jdmg;

/**
 *
 * @author Josue
 */
public class ventanaAdministrar extends javax.swing.JFrame {

    /**
     * Creates new form ventanaAdministrar
     */
    public ventanaAdministrar() {
        dispose();
        ventanaPrincipal Jframe1 = new ventanaPrincipal();
        initComponents();
        eliminarVideos.setVisible(false);
        eliminarImagenes.setVisible(false);
        eliminarMusica.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cantidadTotal = new javax.swing.JTextField();
        textFieldVideo = new javax.swing.JTextField();
        textFieldTotal = new javax.swing.JTextField();
        textFieldFotos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textFieldMusica1 = new javax.swing.JTextField();
        cantidadMusica1 = new javax.swing.JTextField();
        cantidadVideo1 = new javax.swing.JTextField();
        cantidadImagen1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botonDuplicadosFotos = new javax.swing.JButton();
        botonDuplicadosMusica = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        eliminarMusica = new javax.swing.JButton();
        eliminarVideos = new javax.swing.JButton();
        eliminarImagenes = new javax.swing.JButton();
        botonDuplicadosVideo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        eliminarVideosDuplicados3 = new javax.swing.JButton();
        fondoAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(0, 102, 102));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Extensión", "Tamaño", "Ruta"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(102, 0, 102));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 820, 450));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setAutoscrolls(true);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("IMÁGENES:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, -1));

        cantidadTotal.setEditable(false);
        cantidadTotal.setBackground(new java.awt.Color(0, 0, 0));
        cantidadTotal.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        cantidadTotal.setForeground(new java.awt.Color(255, 255, 255));
        cantidadTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadTotalActionPerformed(evt);
            }
        });
        jPanel3.add(cantidadTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 100, 30));

        textFieldVideo.setEditable(false);
        textFieldVideo.setBackground(new java.awt.Color(0, 0, 0));
        textFieldVideo.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jPanel3.add(textFieldVideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 100, 30));

        textFieldTotal.setEditable(false);
        textFieldTotal.setBackground(new java.awt.Color(0, 0, 0));
        textFieldTotal.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jPanel3.add(textFieldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 99, 30));

        textFieldFotos.setEditable(false);
        textFieldFotos.setBackground(new java.awt.Color(0, 0, 0));
        textFieldFotos.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        textFieldFotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFotosActionPerformed(evt);
            }
        });
        jPanel3.add(textFieldFotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 99, 30));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CANTIDAD");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 90, 20));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TOTALES:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 80, 30));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MUSICA:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("VIDEO:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TAMAÑO");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 70, 20));

        textFieldMusica1.setEditable(false);
        textFieldMusica1.setBackground(new java.awt.Color(0, 0, 0));
        textFieldMusica1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        textFieldMusica1.setForeground(new java.awt.Color(255, 255, 255));
        textFieldMusica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMusica1ActionPerformed(evt);
            }
        });
        jPanel3.add(textFieldMusica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 100, 30));

        cantidadMusica1.setEditable(false);
        cantidadMusica1.setBackground(new java.awt.Color(0, 0, 0));
        cantidadMusica1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        cantidadMusica1.setForeground(new java.awt.Color(255, 255, 255));
        cantidadMusica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadMusica1ActionPerformed(evt);
            }
        });
        jPanel3.add(cantidadMusica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 100, 30));

        cantidadVideo1.setEditable(false);
        cantidadVideo1.setBackground(new java.awt.Color(0, 0, 0));
        cantidadVideo1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        cantidadVideo1.setForeground(new java.awt.Color(255, 255, 255));
        cantidadVideo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadVideo1ActionPerformed(evt);
            }
        });
        jPanel3.add(cantidadVideo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 100, -1));

        cantidadImagen1.setEditable(false);
        cantidadImagen1.setBackground(new java.awt.Color(0, 0, 0));
        cantidadImagen1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        cantidadImagen1.setForeground(new java.awt.Color(255, 255, 255));
        cantidadImagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadImagen1ActionPerformed(evt);
            }
        });
        jPanel3.add(cantidadImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 100, 30));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 102));
        jLabel1.setText("DETALLE ARCHIVOS DUPLICADOS");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 380, 250));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonDuplicadosFotos.setBackground(new java.awt.Color(0, 102, 102));
        botonDuplicadosFotos.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        botonDuplicadosFotos.setText("IMÁGENES");
        botonDuplicadosFotos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonDuplicadosFotos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonDuplicadosFotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDuplicadosFotosActionPerformed(evt);
            }
        });
        jPanel1.add(botonDuplicadosFotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 40));

        botonDuplicadosMusica.setBackground(new java.awt.Color(0, 102, 102));
        botonDuplicadosMusica.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        botonDuplicadosMusica.setText("MUSICA");
        botonDuplicadosMusica.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonDuplicadosMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonDuplicadosMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDuplicadosMusicaActionPerformed(evt);
            }
        });
        jPanel1.add(botonDuplicadosMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 40));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("VER DUPLICADOS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        eliminarMusica.setBackground(new java.awt.Color(255, 0, 51));
        eliminarMusica.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        eliminarMusica.setText("ELIMINAR DUPLICADOS");
        eliminarMusica.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarMusica.setEnabled(false);
        jPanel1.add(eliminarMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 210, 40));

        eliminarVideos.setBackground(new java.awt.Color(255, 0, 51));
        eliminarVideos.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        eliminarVideos.setText("ELIMINAR DUPLICADOS");
        eliminarVideos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarVideos.setEnabled(false);
        jPanel1.add(eliminarVideos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 210, 40));

        eliminarImagenes.setBackground(new java.awt.Color(255, 0, 51));
        eliminarImagenes.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        eliminarImagenes.setText("ELIMINAR DUPLICADOS");
        eliminarImagenes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarImagenes.setEnabled(false);
        jPanel1.add(eliminarImagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 210, 40));

        botonDuplicadosVideo.setBackground(new java.awt.Color(0, 102, 102));
        botonDuplicadosVideo.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        botonDuplicadosVideo.setText("VIDEOS");
        botonDuplicadosVideo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonDuplicadosVideo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonDuplicadosVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDuplicadosVideoActionPerformed(evt);
            }
        });
        jPanel1.add(botonDuplicadosVideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 290, 380, 190));

        jButton1.setBackground(new java.awt.Color(0, 153, 102));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton1.setText("REGRESAR");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 100, 30));

        eliminarVideosDuplicados3.setBackground(new java.awt.Color(255, 0, 51));
        eliminarVideosDuplicados3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        eliminarVideosDuplicados3.setText("ELIMINAR SELECCINADO");
        eliminarVideosDuplicados3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(eliminarVideosDuplicados3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 180, 30));

        fondoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/wallpaperbetter.jpg"))); // NOI18N
        fondoAdmin.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(fondoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -350, 1600, 1200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantidadTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadTotalActionPerformed

    private void textFieldFotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFotosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFotosActionPerformed

    private void textFieldMusica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldMusica1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldMusica1ActionPerformed

    private void cantidadMusica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadMusica1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadMusica1ActionPerformed

    private void cantidadVideo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadVideo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadVideo1ActionPerformed

    private void cantidadImagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadImagen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadImagen1ActionPerformed

    private void botonDuplicadosVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDuplicadosVideoActionPerformed
        eliminarVideos.setVisible(true);
        eliminarVideos.setEnabled(true);
        eliminarImagenes.setVisible(false);
        eliminarImagenes.setEnabled(false);
        eliminarMusica.setVisible(false);
        eliminarMusica.setEnabled(false);
        
    }//GEN-LAST:event_botonDuplicadosVideoActionPerformed

    private void botonDuplicadosFotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDuplicadosFotosActionPerformed
        eliminarVideos.setVisible(false);
        eliminarVideos.setEnabled(false);
        eliminarImagenes.setVisible(true);
        eliminarImagenes.setEnabled(true);
        eliminarMusica.setVisible(false);
        eliminarMusica.setEnabled(false);
    }//GEN-LAST:event_botonDuplicadosFotosActionPerformed

    private void botonDuplicadosMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDuplicadosMusicaActionPerformed
        eliminarVideos.setVisible(false);
        eliminarVideos.setEnabled(false);
        eliminarImagenes.setVisible(false);
        eliminarImagenes.setEnabled(false);
        eliminarMusica.setVisible(true);
        eliminarMusica.setEnabled(true);
    }//GEN-LAST:event_botonDuplicadosMusicaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ventanaPrincipal principal = new ventanaPrincipal();
       principal.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ventanaAdministrar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDuplicadosFotos;
    private javax.swing.JButton botonDuplicadosMusica;
    private javax.swing.JButton botonDuplicadosVideo;
    private javax.swing.JTextField cantidadImagen1;
    private javax.swing.JTextField cantidadMusica1;
    private javax.swing.JTextField cantidadTotal;
    private javax.swing.JTextField cantidadVideo1;
    private javax.swing.JButton eliminarImagenes;
    private javax.swing.JButton eliminarMusica;
    private javax.swing.JButton eliminarVideos;
    private javax.swing.JButton eliminarVideosDuplicados3;
    private javax.swing.JLabel fondoAdmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textFieldFotos;
    private javax.swing.JTextField textFieldMusica1;
    private javax.swing.JTextField textFieldTotal;
    private javax.swing.JTextField textFieldVideo;
    // End of variables declaration//GEN-END:variables
}
